/**
 * COC 跑团助手 - 共享类型与常量定义
 * 前后端共用
 */

// ===== 技能名称标准化映射 =====
export const SKILL_NAME_MAP: Record<string, string> = {
  // 战斗技能
  "闪避": "闪避",
  "dodge": "闪避",
  "格斗": "格斗(斗殴)",
  "斗殴": "格斗(斗殴)",
  "brawl": "格斗(斗殴)",
  "手枪": "射击(手枪)",
  "射击手枪": "射击(手枪)",
  "handgun": "射击(手枪)",
  "步枪": "射击(步枪/霰弹枪)",
  "霰弹枪": "射击(步枪/霰弹枪)",
  "rifle": "射击(步枪/霰弹枪)",
  "shotgun": "射击(步枪/霰弹枪)",
  "弓": "射击(弓)",
  "bow": "射击(弓)",
  "投掷": "投掷",
  "throw": "投掷",
  "近战": "格斗(斗殴)",

  // 探索技能
  "侦查": "侦查",
  "spot": "侦查",
  "聆听": "聆听",
  "listen": "聆听",
  "图书馆": "图书馆使用",
  "图书馆使用": "图书馆使用",
  "library": "图书馆使用",
  "跟踪": "追踪",
  "追踪": "追踪",
  "track": "追踪",
  "潜行": "潜行",
  "sneak": "潜行",
  "开锁": "锁匠",
  "锁匠": "锁匠",
  "locksmith": "锁匠",
  "撬锁": "锁匠",
  "妙手": "妙手",
  "sleight": "妙手",
  "乔装": "乔装",
  "disguise": "乔装",
  "估价": "估价",
  "appraise": "估价",

  // 社交技能
  "话术": "话术",
  "talk": "话术",
  "说服": "说服",
  "persuade": "说服",
  "恐吓": "恐吓",
  "intimidate": "恐吓",
  "魅惑": "魅惑",
  "charm": "魅惑",
  "取悦": "魅惑",
  "心理学": "心理学",
  "psychology": "心理学",
  "精神分析": "精神分析",
  "psychoanalysis": "精神分析",

  // 知识技能
  "医学": "医学",
  "medicine": "医学",
  "急救": "急救",
  "first_aid": "急救",
  "历史": "历史",
  "history": "历史",
  "神秘学": "神秘学",
  "occult": "神秘学",
  "克苏鲁神话": "克苏鲁神话",
  "cthulhu_mythos": "克苏鲁神话",
  "cm": "克苏鲁神话",
  "法律": "法律",
  "law": "法律",
  "博物学": "博物学",
  "natural_world": "博物学",
  "自然学": "博物学",
  "物理": "物理",
  "physics": "物理",
  "化学": "化学",
  "chemistry": "化学",
  "生物学": "生物学",
  "biology": "生物学",
  "药学": "药学",
  "pharmacy": "药学",
  "人类学": "人类学",
  "anthropology": "人类学",
  "考古学": "考古学",
  "archaeology": "考古学",
  "电子学": "电子学",
  "electronics": "电子学",
  "工程学": "工程学",
  "engineer": "工程学",
  "天文学": "天文学",
  "astronomy": "天文学",

  // 实用技能
  "汽车": "汽车驾驶",
  "驾驶": "汽车驾驶",
  "汽车驾驶": "汽车驾驶",
  "drive": "汽车驾驶",
  "骑术": "骑术",
  "ride": "骑术",
  "游泳": "游泳",
  "swim": "游泳",
  "攀爬": "攀爬",
  "climb": "攀爬",
  "跳跃": "跳跃",
  "jump": "跳跃",
  "生存": "生存",
  "survival": "生存",
  "机械维修": "机械维修",
  "mech_repair": "机械维修",
  "电气维修": "电气维修",
  "elec_repair": "电气维修",
  "操作重型机械": "操作重型机械",
  "heavy_machinery": "操作重型机械",
  "摄影": "摄影",
  "photography": "摄影",
  "书法": "书法",
  "calligraphy": "书法",
  "美术": "美术",
  "art": "美术",
  "表演": "表演",
  "act": "表演",
  "唱歌": "歌唱",
  "歌唱": "歌唱",
  "sing": "歌唱",
  "写作": "写作",
  "write": "写作",
  "舞蹈": "舞蹈",
  "dance": "舞蹈",
  "烹饪": "厨艺",
  "厨艺": "厨艺",
  "cook": "厨艺",
  "伪造": "伪造",
  "forge": "伪造",

  // 语言技能
  "母语": "母语",
  "native_language": "母语",
  "英语": "英语",
  "english": "英语",
  "拉丁语": "拉丁语",
  "latin": "拉丁语",
  "法语": "法语",
  "french": "法语",
  "德语": "德语",
  "german": "德语",
  "日语": "日语",
  "japanese": "日语",
  "中文": "中文",
  "chinese": "中文",

  // 科学技能
  "计算机": "计算机使用",
  "计算机使用": "计算机使用",
  "computer": "计算机使用",
  "会计": "会计",
  "accounting": "会计",
  "信用评级": "信用评级",
  "credit_rating": "信用评级",
  "信誉": "信用评级",
  "导航": "导航",
  "navigate": "导航",
  "领航": "导航",
  "潜水": "潜水",
  "dive": "潜水",
  "爆破": "爆破",
  "demolitions": "爆破",
  "读唇": "读唇",
  "lip_read": "读唇",
  "催眠": "催眠",
  "hypnosis": "催眠",
  "炮术": "炮术",
  "artillery": "炮术",
  "绳艺": "绳艺",
  "rope_use": "绳艺",
};

// ===== COC 7版 标准技能基础值 =====
export const STANDARD_SKILLS: Record<string, { baseValue: number; category: string }> = {
  "会计": { baseValue: 5, category: "知识" },
  "人类学": { baseValue: 1, category: "知识" },
  "估价": { baseValue: 5, category: "探索" },
  "考古学": { baseValue: 1, category: "知识" },
  "美术": { baseValue: 5, category: "艺术" },
  "摄影": { baseValue: 5, category: "艺术" },
  "表演": { baseValue: 5, category: "艺术" },
  "伪造": { baseValue: 1, category: "犯罪" },
  "天文学": { baseValue: 1, category: "科学" },
  "生物学": { baseValue: 1, category: "科学" },
  "植物学": { baseValue: 1, category: "科学" },
  "化学": { baseValue: 1, category: "科学" },
  "攀岩": { baseValue: 20, category: "运动" },
  "计算机使用": { baseValue: 5, category: "技术" },
  "信用评级": { baseValue: 0, category: "社交" },
  "克苏鲁神话": { baseValue: 0, category: "知识" },
  "乔装": { baseValue: 5, category: "社交" },
  "闪避": { baseValue: 0, category: "战斗" }, // 闪避基础值 = DEX
  "汽车驾驶": { baseValue: 20, category: "技术" },
  "电气维修": { baseValue: 10, category: "技术" },
  "电子学": { baseValue: 1, category: "技术" },
  "工程学": { baseValue: 1, category: "技术" },
  "话术": { baseValue: 5, category: "社交" },
  "格斗(斗殴)": { baseValue: 25, category: "战斗" },
  "射击(手枪)": { baseValue: 20, category: "战斗" },
  "射击(步枪/霰弹枪)": { baseValue: 25, category: "战斗" },
  "射击(弓)": { baseValue: 15, category: "战斗" },
  "射击(机枪)": { baseValue: 10, category: "战斗" },
  "急救": { baseValue: 30, category: "医疗" },
  "历史": { baseValue: 5, category: "知识" },
  "恐吓": { baseValue: 15, category: "社交" },
  "跳跃": { baseValue: 20, category: "运动" },
  "母语": { baseValue: 0, category: "语言" }, // 母语 = EDU
  "法律": { baseValue: 5, category: "知识" },
  "图书馆使用": { baseValue: 20, category: "探索" },
  "聆听": { baseValue: 20, category: "探索" },
  "锁匠": { baseValue: 1, category: "技术" },
  "机械维修": { baseValue: 10, category: "技术" },
  "医学": { baseValue: 1, category: "医疗" },
  "博物学": { baseValue: 10, category: "知识" },
  "导航": { baseValue: 10, category: "技术" },
  "神秘学": { baseValue: 5, category: "知识" },
  "操作重型机械": { baseValue: 1, category: "技术" },
  "说服": { baseValue: 10, category: "社交" },
  "精神分析": { baseValue: 1, category: "医疗" },
  "心理学": { baseValue: 10, category: "社交" },
  "骑术": { baseValue: 5, category: "运动" },
  "妙手": { baseValue: 10, category: "犯罪" },
  "侦查": { baseValue: 25, category: "探索" },
  "潜行": { baseValue: 20, category: "探索" },
  "生存": { baseValue: 10, category: "野外" },
  "游泳": { baseValue: 20, category: "运动" },
  "投掷": { baseValue: 20, category: "战斗" },
  "追踪": { baseValue: 10, category: "探索" },
  "魅惑": { baseValue: 15, category: "社交" },
  "潜水": { baseValue: 1, category: "运动" },
  "爆破": { baseValue: 1, category: "军事" },
  "读唇": { baseValue: 1, category: "感知" },
  "催眠": { baseValue: 1, category: "医疗" },
  "炮术": { baseValue: 1, category: "军事" },
  "绳艺": { baseValue: 5, category: "野外" },
  "歌唱": { baseValue: 5, category: "艺术" },
  "写作": { baseValue: 5, category: "艺术" },
  "舞蹈": { baseValue: 5, category: "艺术" },
  "厨艺": { baseValue: 5, category: "生活" },
};

// ===== 检定结果枚举 =====
export type CheckResult =
  | "fumble"        // 大失败 (100, 或 96-100当目标值>=50时)
  | "failure"       // 失败
  | "success"       // 成功
  | "hard_success"  // 困难成功 (<= 目标值/2)
  | "extreme_success" // 极难成功 (<= 目标值/5)
  | "critical";     // 大成功 (1)

// ===== 难度枚举 =====
export type Difficulty = "normal" | "hard" | "extreme";

// ===== 检定结果的中文显示 =====
export const RESULT_LABELS: Record<CheckResult, string> = {
  fumble: "大失败",
  failure: "失败",
  success: "成功",
  hard_success: "困难成功",
  extreme_success: "极难成功",
  critical: "大成功",
};

// ===== 角色卡属性标准化映射 =====
export const ATTR_NAME_MAP: Record<string, string> = {
  "str": "力量",
  "力量": "力量",
  "strength": "力量",
  "con": "体质",
  "体质": "体质",
  "constitution": "体质",
  "siz": "体型",
  "体型": "体型",
  "size": "体型",
  "dex": "敏捷",
  "敏捷": "敏捷",
  "dexterity": "敏捷",
  "app": "外貌",
  "外貌": "外貌",
  "appearance": "外貌",
  "int": "智力",
  "智力": "智力",
  "intelligence": "智力",
  "灵感": "智力",
  "pow": "意志",
  "意志": "意志",
  "power": "意志",
  "edu": "教育",
  "教育": "教育",
  "education": "教育",
  " luck": "幸运",
  "幸运": "幸运",
  "luck": "幸运",
  "运气": "幸运",
  "hp": "体力",
  "体力": "体力",
  "生命值": "体力",
  "hit_points": "体力",
  "mp": "魔法",
  "魔法": "魔法",
  "magic_points": "魔法",
  "san": "理智",
  "理智": "理智",
  "sanity": "理智",
  "理智值": "理智",
  "san值": "理智",
  "mov": "移动力",
  "移动力": "移动力",
  "movement": "移动力",
  "build": "体格",
  "体格": "体格",
  "db": "伤害加深",
  "伤害加深": "伤害加深",
  "damage_bonus": "伤害加深",
};
